apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: enterprise-shop
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Enterprise Shopping Application Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: backend
      server: https://kubernetes.default.svc
    - namespace: middleware
      server: https://kubernetes.default.svc
    - namespace: frontend
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'networking.k8s.io'
      kind: Ingress
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: 'apps'
      kind: '*'
    - group: 'networking.k8s.io'
      kind: '*'
