apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: middleware-services
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: enterprise-shop
    tier: middleware
spec:
  project: enterprise-shop
  source:
    repoURL: ${GIT_REPO_URL}
    targetRevision: HEAD
    path: k8s/middleware
  destination:
    server: https://kubernetes.default.svc
    namespace: middleware
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
